services:
  zenvi:
    image: zenvi
    build:
      context: .
      dockerfile: Zenvi/Dockerfile
    environment:
      DATABASE_HOST: {DB_HOST}
      DATABASE_PORT: {DB_PORT}
      DATABASE_NAME: {DB_NAME}
      DATABASE_USER: {DB_USER}
      DATABASE_PSWD: {DB_PSWD}

  zenvi-postgres:
    image: postgres:latest
    ports:
      {DB_PORT}:5432
    environment:
      POSTGRES_USER: {DB_USER}
      POSTGRES_PASSWORD: {DB_PSWD}
      POSTGRES_DB: {DB_NAME}
    volumes:
      - zenvi-postgres-data:

volumes:
  zenvi-postgres-data: