version: '3.8'

services:
  zenvi.core:
    image: zenvi
    build:
      context: .
      dockerfile: Zenvi.Webapp/Dockerfile
    environment:
      - DBCONSTRING=${CONNECTION_STRING}
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - zenvidb_data:/var/lib/mysql

volumes:
  zenvidb_data:
