networks:
  zenvinet:
    driver: bridge

services:
  zenvidb:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PSWD}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - ${DATABASE_PATH}:/var/lib/postgresql/data
    networks:
      - zenvinet

  zenvi.core:
    build:
      context: .
      dockerfile: Zenvi.Core/Dockerfile
    environment:
      DATABASE_HOST: zenvidb
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PSWD: ${DATABASE_PSWD}
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - zenvidb
    networks:
      - zenvinet
    volumes:
      - ${APPDATA_PATH}:/data
      - ${CONFIG_PATH}:/config

  zenvi.client:
    build:
      context: .
      dockerfile: Zenvi.Client/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - zenvi.core
    networks:
      - zenvinet