#+title: Starting Point
#+subtitle: Initial Idea for Zenvi
#+author: Clay Gomera
#+latex_class: article
#+latex_class_options: [letterpaper,12pt]
#+latex_header: \usepackage[margin=1in]{geometry}
#+latex_header: \usepackage{fontspec}
#+latex_header: \setmainfont{Carlito} % or any other font you prefer
#+latex_compiler: xelatex
#+OPTIONS: toc:nil date:nil num:nil
#+description: Documentation document that describes the initial idea for this project

* Project Context

Zenvi is the final project for the Web Application Development course. The
choice of this project arose from the top 100 most visited websites according to
Similarweb, a recommendation from the professor to inspire us in the type of
website to develop. My choice was to create a clone of Twitter, a social network
for microblogging and private messaging.

* Project Details

** Adaptation

To differentiate the Zenvi project from what already exists, it has been decided
to focus on the following aspects:

- *Privacy*: Zenvi will be a private and completely independent social network,
  designed to be used by closed groups such as families or friends.
- *Self-Hosted Model*: Zenvi will be self-hosted, meaning each group can manage
  their own server, thereby ensuring greater control over data and privacy.
- *Simplicity*: Zenvi will prioritize simplicity and efficiency over an
  overwhelming amount of features, focusing solely on the social aspect of the
  platform.

** Ideas

Zenvi will include a series of specific features to ensure its functionality and
suitability for the stated objectives.

*** Access and Administration

- *Login*: The site will only be accessible through login, emphasizing the
  privacy of the social network.
- *Account Management*: The administrator will be able to manage all accounts in
  the server.
- *Authentication*: Users will need to confirm their email address before logging
  into the site. After registering, a confirmation email will be sent to the
  user.
- *Two Factor Authentication*: Users will be able to enable TOTP based two-factor
  authentication from their profile settings, but by default, email-based
  two-factor authentication is enforced for every user.
- *Single Sign-On*: Users will be able to sign in using Google or Microsoft.

*** Home Page

- *Main Feed*: Similar to Twitter, the home page will display a global feed
  that includes all posts on the server. This feed will not have default
  filters, suitable for small communities. Users can follow other users and
  filter the feed to show only the posts from those they follow.

*** Main Features

Zenvi users will be able to perform the following actions:

1. *Account and User Profile Management*: Edit personal information and configure
   account preferences.
2. *View Main Feed (Home)*: Access the home page with the global or filtered feed.
3. *Interact with Profiles*: View and follow other users' profiles.
4. *Private Chats*: Send and receive private messages with other users.
5. *Chat Rooms*: Create and participate in group chat rooms.
6. *Multimedia in Chats*: Send photos through chats.
7. *Post*: Post content, with a limit of 800 characters per post. Include hashtags
   to categorize content and increase visibility.
8. *Multimedia in Posts*: Upload photos in posts, with a limit of 10 photos per
   post.
9. *Comment on Posts*: Comment on posts with a limit of 500 characters per
   comment.
10. *Mentions in Posts*: Mention other users in posts, notifying them of the
    mention.
11. *Hashtags in Posts*: Use hashtags within posts to tag relevant topics, making
    the posts searchable by those hashtags.
12. *Search by Hashtags*: Search for posts using hashtags to find relevant
    content.
13. *Search by Users and Content*: Search for posts by keywords, users, and
    content to find relevant information across the platform.
14. *Favorite Posts*: Mark a post as a favorite, which then will appear in the
    favorites section.
15. *Like a Post*: Give a like to a post.
16. *Edit a Post*: Correct or update the content of a post, regardless of how old
    it is.
17. *Report Posts*: Report inappropriate posts to administrators for review.
18. *Notification Management*: Manage notifications including mentions in posts,
    new followers, and messages. These notifications will be in real-time.

*** Post Metadata

Posts in Zenvi will contain the following metadata:

1. *Publication Date*: Record of the date and time the post was made.
2. *Modification Date*: If the post was edited, the date and time of the last
   modification will be shown.
3. *Likes*: Because users can "like" any post, the total number of "likes" will be
   visible on each post.
4. *Comments*: Comments on posts will be treated as posts themselves but will be
   linked to the original post and include a mention to the original author. If
   a comment is a reply to another comment it would be treated the same way.

*** Chat Metadata

Chats in Zenvi will contain the following metadata:

1. *Message Date*: Record of the date and time each message was sent.
2. *Sender Information*: The username of the sender.

*** Administrator Features

Administrators in Zenvi will be able to perform the following actions:

1. *User Management*: Create, delete, and manage user accounts.
2. *Content Moderation*: Review and remove inappropriate content or posts.
3. *Review Reports*: View and manage reports of inappropriate posts submitted by
   users.
4. *Manage Settings*: Configure system settings, including privacy policies and
   security measures.
5. *Send notice*: Send a notice to all users in the server through a notification.
6. *Ban User*: Ban users for a specified duration for violating policies.

* Conclusion

Zenvi is envisioned as a private, self-hosted social network with a strong focus
on privacy and community control. With these features, it seeks to offer a
differentiated alternative to existing social networks, suitable for small
communities that value privacy and control over their data.

* Inspirations

I'm using these videos as inspiration material:

- https://www.youtube.com/watch?v=rOa2FKR-rGA
- https://www.youtube.com/watch?v=hYIH1qXxJtY
